language: swift
osx_image: xcode9
script: xcodebuild -workspace SKFoundation.xcworkspace -scheme SKFoundation -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 8' -configuration Debug build
